AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  subway-monitor

Parameters:
  ApiKey:
    Type: String

Resources:
  SubwayMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: SubwayMonitor/
      Runtime: python3.8
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
          DYNAMODB_TABLE: !Ref DynamoDBTable
          SMS_SENDER_TOPIC_ARN: !Ref SMSSender
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 1
            StartingPosition: TRIM_HORIZON

  RequestHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonSNSFullAccess
        - AmazonDynamoDBFullAccess
      CodeUri: RequestHandler/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          SMS_SENDER_TOPIC_ARN: !Ref SMSSender
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SMSReciever

  SMSReciever:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SMSRecieverTopic

  SMSSender:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SMSSenderTopic
      Subscription:
        - Endpoint: 17707102162
          Protocol: sms

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: N
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
        - AttributeName: status
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
