AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  subway-monitor

Parameters:
  ApiKey:
    Type: String

Resources:
  SubwayMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonSNSFullAccess
        - AmazonDynamoDBFullAccess
      CodeUri: SubwayMonitor/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
          SMS_SENDER_TOPIC_ARN: !Ref SMSSender
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SMSReciever

  SMSReciever:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SMSRecieverTopic

  SMSSender:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SMSSenderTopic
      Subscription:
        - Endpoint: 17707102162
          Protocol: sms

